### ISSUE TITLE
Warning: Functions are not valid as a React child

### ISSUE THREAD

**Issue by anjalsan** [InterfaceKit/react-native-js-bottom-sheet#2]
it's working. but I'm getting this warning

> Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

**Comment by a-morenovalls** [comment]
Hi @anjalsan , this issue is confirmed, when we have time, we'll work it out. If you found the problem and solved it, can you do a PR? Thanks!
