### ISSUE TITLE
Android material designs

### ISSUE THREAD

**Issue by Noitidart** [InterfaceKit/react-native-js-bottom-sheet#3]
Thanks for such a superb module. This was so needed because we have iOS ActionSheet out of the box of react native but not the native `BottomSheetDialogFragment` element of Android? - https://developer.android.com/reference/android/support/design/widget/BottomSheetDialogFragment.html

Would it possible to add cusotmizations to match material styles of what I found in official guidleines here - https://material.io/guidelines/components/bottom-sheets.html#bottom-sheets-modal-bottom-sheets

* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3NWNQcUo1TnhhaWs/components-bottomsheets-modal1.png
* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3UzA3RDctV2k0YUk/components-bottomsheets-modal2.png
* https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3OWxLQ182ZTNxZGM/components-bottomsheets-modal3.png
* https://github.com/soarcn/BottomSheet/raw/master/art/image.png?raw=true

**Comment by a-morenovalls** [comment]
Hi @Noitidart ! We were planning to add different customisations options to create for example a grid modal. By now, you can modify the source code to archive this. About the native solution you commented, it would be a great idea for the React Native team to implement it, but for now we have to use other solutions provided by the community.

**Comment by Noitidart** [comment]
Thank you sir very much for your fast and positive reply! I will continue to be a user of this very much needed module! Should I close this out or leave it open? Thank you so much!

**Comment by a-morenovalls** [comment]
I'm glad that you like the library. It can be closed, we'll take into account the possible options to improve the library. If you have ideas you could make a PR about new features and we will take them into account. Greetings!

**Comment by Noitidart** [comment]
Thanks again very much! I will share feedback as I use this more. :)
